version: "3.7"
services:
    postgres:
        image: postgres:12.0-alpine
        environment:
            - POSTGRES_USER=db_capstone
            - POSTGRES_PASSWORD=db_capstone
            - POSTGRES_DB=db_capstone
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - postgresdata:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
    scraper_1:
        image: python:3.9.1
        depends_on:
            - postgres
        #entrypoint: echo hi
        tty: true
        volumes:
            - ./scraper/:/opt/scr        

volumes:
    postgresdata: